##https://github.com/actions/cache
###https://github.com/marketplace/actions/setup-github-cli
name: cache
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # Add caching
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        ## format for chceking and calling cache: steps.<step_id>.outputs.<output_name>
        run: npm ci
      - name: Test code
        run: npm run test
      - run: npm run build
  checkout:
    name: Checkout code
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}" ### This step outputs the event data
      - name: Get code
        uses: actions/checkout@v3
  install:
    name: Install Dependencies
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3 ##T get list of all the actions https://github.com/actions/cache
        with:
          path: ~/.npm ##This is the path to cache the npm dependencies, the dependencies are stored in the ~/.npm directory
          key: depend-node-modules-${{hashFiles('**/package-lock.json')}} ### This is the key for the cache, it is based on the hash of the package-lock.json file, if the file changes, the cache is discarded and a new cache is created
          ###key also, suggest if the ache should be discarded or not, if the key changes, the cache is discarded and a new cache is createdhence give the name of cache that dinamic and can change as cache is discarded if the key changes
          ## hash files is used to create a unique key for the cache, if the package-lock.json file changes, the cache is discarded and a new cache is created and we are not using the old cache stored in the ~/.npm directory
      - name: Install dependencies
        run: npm ci

  clear:
    runs-on: ubuntu-latest
    needs: install
    permissions:
      actions: write
    steps:
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
      - name: Delete branchâ€‘specific caches
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Must have repo scope
        run: |
          gh cache list \
            --repo "${{ github.repository }}" \
            --ref "refs/heads/${{ github.ref_name }}" \
            --limit 100 --json id --jq '.[].id' \
          | while read cacheId; do
              gh cache delete "$cacheId" --repo "${{ github.repository }}"
            done
