name: cache
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add caching
      - run: npm ci
      - run: npm run build

  clear:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: write
    steps:
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
      - name: Delete branchâ€‘specific caches
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Must have repo scope
        run: |
          gh cache list \
            --repo "${{ github.repository }}" \
            --ref "refs/heads/${{ github.ref_name }}" \
            --limit 100 --json id --jq '.[].id' \
          | while read cacheId; do
              gh cache delete "$cacheId" --repo "${{ github.repository }}"
            done